#!/usr/bin/env bash
# Display information about subdomains
print_dom ()
{
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | grep "$2" | awk -v sd="$2" '{print "The subdomain " sd " is a " $4 " record and points to " $5}'
}

if [ "$2" ]
then
	print_dom "$1" "$2"
else
	print_dom "$1" "www"
	print_dom "$1" "lb-01"
	print_dom "$1" "web-01"
	print_dom "$1" "web-02"
fi