#!/usr/bin/env bash
#Web servers are the piece of software generating and serving HTML pages, let’s install one!

sudo apt-get update
sudo apt-get install nginx -y
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart