#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get install nginx -y
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default
sudo service nginx restart