#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
apt-get update
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/sever_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default
service nginx restart