#!/usr/bin/env bash
#Nginx must be running, and listening on port 80 of all the server's active IPv4 IPs
sudo apt update
sudo apt -y install nginx
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
