#!/usr/bin/env bash
#Nginx must be running, and listening on port 80 of all the server's active IPv4 IPs
sed -i "s/listen 8080 default_server;\nlisten [::]:8080 default_server;/listen 80 default_server;\nlisten [::]:80 default_server;" /etc/nginx/sites-available/default
sudo service nginx restart
