#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet.
sudo apt update
sudo apt -y install nginx
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
